CREATE TABLE datasus.sih_refined.tb_datasus_sih (
    UF_ZI CHAR(7),
    ANO_CMPT CHAR(4),
    MES_CMPT CHAR(2),
    ESPEC CHAR(2),
    desc_leito VARCHAR(100), -- Nova coluna
    CGC_HOSP CHAR(14),
    N_AIH CHAR(13),
    desc_tipo_aih VARCHAR(30), -- Nova coluna
    IDENT CHAR(1),
    CEP CHAR(8),
    MUNIC_RES CHAR(6),
    desc_uf_residencia VARCHAR(100), -- Nova coluna
    desc_municipio_residencia VARCHAR(100), -- Nova coluna
    desc_regiao_residencia VARCHAR(100), -- Nova coluna
    DT_NASC date,
    SEXO CHAR(1),
    desc_sexo VARCHAR(50),
    UTI_MES_IN INTEGER,
    UTI_MES_AN INTEGER,
    UTI_MES_AL INTEGER,
    UTI_MES_TO INTEGER,
    MARCA_UTI CHAR(2),
    UTI_INT_IN INTEGER,
    UTI_INT_AN INTEGER,
    UTI_INT_AL INTEGER,
    UTI_INT_TO INTEGER,
    DIAR_ACOM INTEGER,
    QT_DIARIAS INTEGER,
    PROC_SOLIC CHAR(10),
    desc_procedimento_solicitado VARCHAR(250), -- Nova coluna
    PROC_REA CHAR(10),
    desc_procedimento_realizado VARCHAR(250), --Nova coluna
    VAL_SH NUMERIC(8,2),
    VAL_SP NUMERIC(8,2),
    VAL_SADT NUMERIC(8,2),
    VAL_RN NUMERIC(8,2),
    VAL_ACOMP NUMERIC(20,2),
    VAL_ORTP NUMERIC(8,2),
    VAL_SANGUE NUMERIC(8,2),
    VAL_SADTSR NUMERIC(8,2),
    VAL_TRANSP NUMERIC(8,2),
    VAL_OBSANG NUMERIC(8,2),
    VAL_PED1AC NUMERIC(8,2),
    VAL_TOT NUMERIC(9,2),
    VAL_UTI NUMERIC(8,2),
    US_TOT NUMERIC(8,2),
    DT_INTER date,
    DT_SAIDA date,
    DIAG_PRINC CHAR(4),
    desc_diag_principal_capitulo VARCHAR(250), --Nova coluna
    desc_diag_principal_categoria VARCHAR(250), --Nova coluna
    desc_diag_principal_subcategoria VARCHAR(100), --Nova coluna
    DIAG_SECUN CHAR(4),
    COBRANCA CHAR(2),
    NATUREZA CHAR(2),
    NAT_JUR CHAR(4),
    GESTAO CHAR(1),
    RUBRICA INTEGER,
    IND_VDRL CHAR(1),
    MUNIC_MOV CHAR(7),
    desc_uf_atendimento VARCHAR(100),-- Nova coluna
    desc_municipio_atendimento VARCHAR(100),-- Nova coluna
    desc_regiao_atendimento VARCHAR(100), -- Nova coluna
    COD_IDADE CHAR(1),
    IDADE INTEGER,
    DIAS_PERM INTEGER,
    MORTE INTEGER,
    NACIONAL CHAR(3),
    NUM_PROC CHAR(4),
    CAR_INT CHAR(2),
    TOT_PT_SP INTEGER,
    CPF_AUT CHAR(11),
    HOMONIMO CHAR(1),
    NUM_FILHOS INTEGER,
    INSTRU CHAR(1),
    CID_NOTIF CHAR(4),
    CONTRACEP1 CHAR(2),
    CONTRACEP2 CHAR(2),
    GESTRISCO CHAR(1),
    INSC_PN CHAR(12),
    SEQ_AIH5 INTEGER,
    CBOR CHAR(6),
    CNAER CHAR(3),
    VINCPREV CHAR(1),
    GESTOR_COD CHAR(5),
    GESTOR_TP CHAR(1),
    GESTOR_CPF CHAR(15),
    GESTOR_DT date,
    CNES CHAR(7),
    CNPJ_MANT CHAR(14),
    INFEHOSP CHAR(1),
    CID_ASSO CHAR(4),
    CID_MORTE CHAR(4),
    COMPLEX CHAR(2),
    desc_complexidade VARCHAR(100),  -- Nova coluna
    FINANC CHAR(2),
    FAEC_TP CHAR(6),
    REGCT CHAR(4),
    RACA_COR CHAR(4),
    ETNIA CHAR(4),
    SEQUENCIA INTEGER,
    REMESSA CHAR(21),
    AUD_JUST VARCHAR(100),
    SIS_JUST VARCHAR(100),
    VAL_SH_FED NUMERIC(10,2),
    VAL_SP_FED NUMERIC(10,2),
    VAL_SH_GES NUMERIC(10,2),
    VAL_SP_GES NUMERIC(10,2),
    VAL_UCI NUMERIC(10,2),
    MARCA_UCI char(2),
    DIAGSEC1 char(4),
    DIAGSEC2 char(4),
    DIAGSEC3 char(4),
    DIAGSEC4 char(4),
    DIAGSEC5 char(4),
    DIAGSEC6 char(4),
    DIAGSEC7 char(4),
    DIAGSEC8 char(4),
    DIAGSEC9 char(4),
    TPDISEC1 char(1),
    TPDISEC2 char(1),
    TPDISEC3 char(1),
    TPDISEC4 char(1),
    TPDISEC5 char(1),
    TPDISEC6 char(1),
    TPDISEC7 char(1),
    TPDISEC8 char(1),
    TPDISEC9 char(1),
    DOWNLOADED_AT timestamp
);